import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Header from '@/components/layout/Header';
import Card from '@/components/common/Card';
import { useState } from 'react';
import PostModal from '@/components/common/PostModal';

const inter = Inter({ subsets: ['latin'] });

interface Post {
  title: string;
  content: string;
}

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [posts, setPosts] = useState<Post[]>([]);

  const handleOpenModal = () => setIsModalOpen(true);
  const handleCloseModal = () => setIsModalOpen(false);

  const handleAddPost = (newPost: Post) => {
    setPosts((prevPosts) => [...prevPosts, newPost]);
    handleCloseModal();
  };

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className="text-4xl font-bold text-center my-8">Welcome to the Home Page!</h1>

        <section className="my-8">
          <h2 className="text-2xl font-semibold mb-4">Our Services</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card
              title="Web Development"
              content="Building modern and responsive web applications using Next.js, TypeScript, and Tailwind CSS."
            />
            <Card
              title="UI/UX Design"
              content="Creating intuitive and engaging user interfaces for a seamless user experience."
            />
            <Card
              title="API Integration"
              content="Seamlessly connecting your application with external services and APIs."
            />
          </div>
        </section>

        <section className="my-8">
          <h2 className="text-2xl font-semibold mb-4">Add a New Post</h2>
          <button
            onClick={handleOpenModal}
            className="px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
          >
            Create New Post
          </button>
          <PostModal isOpen={isModalOpen} onClose={handleCloseModal} onAddPost={handleAddPost} />

          {posts.length > 0 && (
            <div className="mt-8">
              <h3 className="text-xl font-medium mb-4">Your Recent Posts:</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {posts.map((post, index) => (
                  <Card key={index} title={post.title} content={post.content} />
                ))}
              </div>
            </div>
          )}
        </section>
      </main>
    </>
  );
}